name: Runway.team Build Uploader
description: Upload a build to Runway.team's build distribution service
author: JackoPlane

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  apiKey:
    description: Your Runway.team API key
    required: true
  appId:
    description: Runway application ID
    required: true
  bucketId:
    description: Runway bucket ID
    required: true
  filePath:
    description: Path to the build file to upload
    required: true
  testerNotes:
    description: Notes to include with the build
    required: false

# Define your outputs here.
# outputs:
#   time:
#     description: Your output description here

runs:
  using: node20
  main: dist/index.js
